spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:h2/db/*.sql
    data: classpath:h2/data/*.sql
    url: jdbc:h2:mem:mgmdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: sa
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  rabbitmq:
    host : localhost
    port : 5672
    username : guest
    password : guest
#  sleuth:
#    sampler:
#      probability: 1

server:
  port : 8089
logging:
  config : classpath:logback-test.xml


eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:9000/eureka

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  httpclient:
    enabled : false
  okhttp:
    enabled : true

feign:
  hystrix:
    # feign熔断器开关
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #断路器的超时时间ms,默认1000
            timeoutInMilliseconds: 4000
      circuitBreaker:
        #当在配置时间窗口内达到此数量的失败后，进行短路
        requestVolumeThreshold: 20
        #出错百分比阈值，当达到此阈值后，开始短路。默认50%）
        errorThresholdPercentage: 50%
        #短路多久以后开始尝试是否恢复，默认5s）-单位ms
        sleepWindowInMilliseconds: 5000